"""Add sessions table and link to conversations

Revision ID: 3611aa674ede
Revises: 0d3ee0b48627
Create Date: 2025-06-08 20:50:37.853278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3611aa674ede'
down_revision = '0d3ee0b48627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_session_id'), ['session_id'], unique=True)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_uuid', sa.String(length=36), nullable=False))
        batch_op.drop_index(batch_op.f('ix_conversations_session_id'))
        batch_op.create_foreign_key('fk_conversations_session_uuid_sessions', 'sessions', ['session_uuid'], ['session_id'])
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint('fk_conversations_session_uuid_sessions', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_conversations_session_id'), ['session_id'], unique=False)
        batch_op.drop_column('session_uuid')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_session_id'))

    op.drop_table('sessions')
    # ### end Alembic commands ###
